version: 2
executorType: docker
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/uw-labs/strongbox

    steps:
      - type: setup-docker-engine
      - checkout

      - run:
          name: Run unit tests
          command: make test 

      - run: go build

  deployment:
    tag:
      tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: release
          command: "curl -sL https://git.io/goreleaser | bash"

